root: true
extends:
  - eslint:recommended
  - google
  - plugin:prettier/recommended
plugins:
  - import
  - prettier
env:
  browser: true
  node: false
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2018
  sourceType: module
globals:
  PRODUCTION: readonly
