name: Fugu Journal Build and Deploy

on:
  push:
    paths:
      - 'fugu-journal/**/*'
      - .github/workflows/fugu-journal.yml
  pull_request:
    paths:
      - 'fugu-journal/**/*'
      - .github/workflows/fugu-journal.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Switch Node Version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        working-directory: ./fugu-journal
        run: |
          npm ci
      - name: Build and Test
        working-directory: ./fugu-journal
        run: |
          npm run build --if-present
        env:
          CI: true
      - name: Deploy to Firebase
        if: success() && github.ref == 'refs/heads/master'
        working-directory: ./fugu-journal
        run: npx -p firebase-tools firebase deploy --token ${FIREBASE_TOKEN}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
